/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData explore = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_squared = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_rect = IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf302, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_bird = IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icq = IconData(0xf304, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yandex = IconData(0xf305, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yandex_rect = IconData(0xf306, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_text = IconData(0xf307, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf308, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleplus_rect = IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vkontakte_rect = IconData(0xf30a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype = IconData(0xf30b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData odnoklassniki = IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData odnoklassniki_rect = IconData(0xf30d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo_rect = IconData(0xf30e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo = IconData(0xf30f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr_rect = IconData(0xf310, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr = IconData(0xf311, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendfeed = IconData(0xf312, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendfeed_rect = IconData(0xf313, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger = IconData(0xf314, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger_rect = IconData(0xf315, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deviantart = IconData(0xf316, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jabber = IconData(0xf317, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lastfm = IconData(0xf318, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lastfm_rect = IconData(0xf319, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf31a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_rect = IconData(0xf31b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picasa = IconData(0xf31c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wordpress = IconData(0xf31d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf31e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_filled = IconData(0xf31f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diigo = IconData(0xf320, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xf321, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_rect = IconData(0xf322, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tudou = IconData(0xf323, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youku = IconData(0xf324, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData win8 = IconData(0xf325, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amex = IconData(0xf326, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover = IconData(0xf327, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa = IconData(0xf328, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mastercard = IconData(0xf329, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData houzz = IconData(0xf32a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bandcamp = IconData(0xf32b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepen = IconData(0xf32c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
